[workspace]
git_release_enable = true
changelog_update = false

[[package]]
name = "dial9-tokio-telemetry"
changelog_update = true
changelog_path = "CHANGELOG.md"
changelog_include = ["dial9-perf-self-profile", "dial9-trace-format"]
version_group = "dial9"

[[package]]
name = "dial9-macro"
changelog_update = false
version_group = "dial9"

[[package]]
name = "dial9-perf-self-profile"
changelog_update = false
version_group = "dial9"

[[package]]
name = "dial9-trace-format"
changelog_update = false
version_group = "dial9"

[[package]]
name = "dial9-trace-format-derive"
changelog_update = false
version_group = "dial9"

[[package]]
name = "dial9-viewer"
changelog_update = false
version_group = "dial9"
