use clap::{Parser, Subcommand};
use std::path::PathBuf;

mod skills {
    // Generated by build.rs from skills/ and toolkit/ directories
    include!(concat!(env!("OUT_DIR"), "/skill_files.rs"));
    include!(concat!(env!("OUT_DIR"), "/toolkit_files.rs"));

    /// Look up a skill segment by name. Returns the content if found.
    pub fn get(name: &str) -> Option<&'static str> {
        SKILL_FILES
            .iter()
            .find(|(n, _, _)| *n == name)
            .map(|(_, _, content)| *content)
    }
}

#[derive(Parser, Debug)]
#[command(
    name = "dial9-viewer",
    about = "S3 trace browser and viewer for dial9-tokio-telemetry"
)]
pub struct Cli {
    #[command(subcommand)]
    command: Option<Commands>,

    /// Port to listen on (when running without a subcommand)
    #[arg(long, default_value = "3000", global = true)]
    port: u16,

    /// S3 bucket name (when running without a subcommand)
    #[arg(long, global = true)]
    bucket: Option<String>,

    /// S3 key prefix (when running without a subcommand)
    #[arg(long, global = true)]
    prefix: Option<String>,

    /// Directory containing UI static files (when running without a subcommand)
    #[arg(long, default_value = "ui", global = true)]
    ui_dir: PathBuf,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Agent skill documentation and analysis toolkit
    Agents {
        #[command(subcommand)]
        action: Option<AgentsAction>,
    },
    /// Start the web server
    Serve {
        /// Port to listen on
        #[arg(long, default_value = "3000")]
        port: u16,

        /// S3 bucket name (if omitted, bucket must be specified per-request)
        #[arg(long)]
        bucket: Option<String>,

        /// S3 key prefix to filter traces
        #[arg(long)]
        prefix: Option<String>,

        /// Directory containing UI static files
        #[arg(long, default_value = "ui")]
        ui_dir: PathBuf,
    },
}

#[derive(Subcommand, Debug)]
enum AgentsAction {
    /// Copy the analysis toolkit (JS modules + analyze.js) to a directory
    Toolkit {
        /// Directory to write toolkit files into (created if missing)
        path: PathBuf,
    },
    /// Print a specific skill segment
    Skill {
        /// Segment name: loading, analysis, recipes, red-flags
        name: String,
    },
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Some(Commands::Agents { action }) => match action {
            None => print!("{}", skills::HEADER),
            Some(AgentsAction::Toolkit { path }) => {
                std::fs::create_dir_all(&path)?;
                for (name, content) in skills::TOOLKIT_FILES {
                    std::fs::write(path.join(name), content)?;
                }
                let abs = std::fs::canonicalize(&path)?;
                eprintln!("Toolkit written to {}", abs.display());
                eprintln!("Run: node {}/analyze.js <trace.bin>", abs.display());
            }
            Some(AgentsAction::Skill { name }) => match skills::get(&name) {
                Some(content) => print!("{}", content),
                None => {
                    eprintln!("Unknown segment: {name}");
                    eprintln!("Available segments:");
                    for (name, title, _) in skills::SKILL_FILES {
                        eprintln!("  {name:12} — {title}");
                    }
                    std::process::exit(1);
                }
            },
        },
        Some(Commands::Serve {
            port,
            bucket,
            prefix,
            ui_dir,
        }) => return serve(port, bucket, prefix, ui_dir).await,
        None => return serve(cli.port, cli.bucket, cli.prefix, cli.ui_dir).await,
    }
    Ok(())
}

async fn serve(
    port: u16,
    bucket: Option<String>,
    prefix: Option<String>,
    ui_dir: PathBuf,
) -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "dial9_viewer=info".parse().unwrap()),
        )
        .init();

    let ui_dir = if ui_dir.exists() {
        ui_dir
    } else if let Ok(exe) = std::env::current_exe() {
        let candidate = exe.parent().unwrap_or(exe.as_ref()).join(&ui_dir);
        if candidate.exists() {
            candidate
        } else {
            ui_dir
        }
    } else {
        ui_dir
    };

    let backend = dial9_viewer::storage::S3Backend::from_env().await;
    let app_state = dial9_viewer::server::AppState::new(
        std::sync::Arc::new(backend),
        bucket.clone(),
        prefix.clone(),
    );

    let app = dial9_viewer::server::router(app_state, &ui_dir);

    let listener = tokio::net::TcpListener::bind(("0.0.0.0", port)).await?;
    tracing::info!(port, ui_dir = %ui_dir.display(), "dial9-viewer listening");
    println!("\n  → http://localhost:{}\n", port);
    if let Some(bucket) = &bucket {
        tracing::info!(%bucket, "default bucket");
    }

    axum::serve(listener, app)
        .with_graceful_shutdown(shutdown_signal())
        .await?;

    Ok(())
}

async fn shutdown_signal() {
    tokio::signal::ctrl_c()
        .await
        .expect("failed to install CTRL+C handler");
    tracing::info!("shutting down");
}
